import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  admins: defineTable({
    username: v.string(),
    password_hash: v.string(),
  }).index("by_username", ["username"]),

  sessions: defineTable({
    admin_id: v.id("admins"),
    token: v.string(),
    expires_at: v.number(),
  }).index("by_token", ["token"]),

  jobs: defineTable({
    title: v.string(),
    department: v.string(),
    location: v.string(),
    experience: v.string(),
    description: v.string(),
    type: v.string(),
    skills: v.string(),
    status: v.union(v.literal("Open"), v.literal("Closed")),
  }),

  applications: defineTable({
    job_id: v.string(),
    job_title: v.string(),
    candidate_name: v.string(),
    email: v.string(),
    phone: v.string(),
    current_location: v.string(),
    skills: v.string(),
    resume_link: v.string(),
    github_link: v.optional(v.string()),
    portfolio_link: v.optional(v.string()),
    current_company: v.optional(v.string()),
    current_ctc: v.optional(v.string()),
    expected_ctc: v.optional(v.string()),
    notice_period: v.optional(v.string()),
    experience: v.optional(v.string()),
    current_position: v.optional(v.string()),
    cover_letter: v.optional(v.string()),
    applied_at: v.number(),
  }).index("by_job", ["job_id"]),

  employees: defineTable({
    name: v.string(),
    role: v.string(),
    email: v.string(),
    headline: v.string(),
    employmentType: v.union(
      v.literal("Full-time"),
      v.literal("Part-time"),
      v.literal("Intern"),
      v.literal("Contract")
    ),
    profileImageId: v.optional(v.id("_storage")),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    linkedinUrl: v.optional(v.string()),
    githubUrl: v.optional(v.string()),
    portfolioUrl: v.optional(v.string()),
    experience: v.string(),
    skills: v.array(v.string()),
    industries: v.array(v.string()),
    bio: v.string(),
    projects: v.array(
      v.object({
        name: v.string(),
        description: v.string(),
        technologies: v.array(v.string()),
      })
    ),
    hobbies: v.array(v.string()),
    quote: v.string(),
    funFact: v.string(),
    preferredContact: v.array(v.string()),
    serviceIds: v.array(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }),

  services: defineTable({
    serviceId: v.string(),
    title: v.string(),
    description: v.string(),
    heroDescription: v.string(),
    features: v.array(v.string()),
    technologies: v.array(v.object({ name: v.string(), icon: v.string() })),
    startingPrice: v.string(),
    deliveryTime: v.string(),
    imageId: v.optional(v.id("_storage")),
    imageUrl: v.optional(v.string()),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    benefits: v.array(v.string()),
    process: v.array(
      v.object({ step: v.number(), title: v.string(), description: v.string() })
    ),
    faqs: v.array(v.object({ question: v.string(), answer: v.string() })),
    teamMembers: v.array(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }).index("by_serviceId", ["serviceId"]),

  blogPosts: defineTable({
    slug: v.string(),
    title: v.string(),
    excerpt: v.string(),
    content: v.string(),
    author: v.string(),
    authorRole: v.string(),
    date: v.string(),
    readTime: v.string(),
    category: v.string(),
    tags: v.array(v.string()),
    imageId: v.optional(v.id("_storage")),
    imageUrl: v.optional(v.string()),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    featured: v.boolean(),
    isActive: v.boolean(),
  }).index("by_slug", ["slug"]),

  products: defineTable({
    slug: v.string(),
    name: v.string(),
    tagline: v.string(),
    description: v.string(),
    longDescription: v.string(),
    what_it_does: v.optional(v.string()),
    purpose: v.optional(v.string()),
    summary: v.optional(v.string()),
    functionality: v.optional(v.array(v.string())),
    screens: v.optional(v.array(v.object({
      name: v.string(),
      desc: v.string(),
      imageId: v.optional(v.id("_storage")),
      imageUrl: v.optional(v.string()),
      cloudinaryPublicId: v.optional(v.string()),
      cloudinarySecureUrl: v.optional(v.string()),
    }))),
    heroImageId: v.optional(v.id("_storage")),
    heroImageUrl: v.optional(v.string()),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    siteUrl: v.optional(v.string()),
    features: v.array(v.object({ title: v.string(), description: v.string() })),
    benefits: v.array(v.string()),
    useCases: v.array(v.string()),
    techStack: v.array(v.string()),
    faq: v.array(v.object({ q: v.string(), a: v.string() })),
    isActive: v.boolean(),
    order: v.number(),
  }).index("by_slug", ["slug"]),

  caseStudies: defineTable({
    caseId: v.string(),
    title: v.string(),
    client: v.string(),
    category: v.string(),
    type: v.string(),
    description: v.string(),
    fullDescription: v.string(),
    technologies: v.array(v.string()),
    results: v.array(v.object({ metric: v.string(), description: v.string() })),
    year: v.string(),
    duration: v.string(),
    link: v.optional(v.string()),
    featured: v.boolean(),
    imageIds: v.array(v.id("_storage")),
    cloudinaryImages: v.optional(v.array(v.object({ publicId: v.string(), secureUrl: v.string() }))),
    isActive: v.boolean(),
    order: v.number(),
  }).index("by_caseId", ["caseId"]),

  faq: defineTable({
    question: v.string(),
    answer: v.string(),
    category: v.optional(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }),

  leadership: defineTable({
    name: v.string(),
    role: v.string(),
    initials: v.string(),
    experience: v.string(),
    specialization: v.string(),
    vision: v.string(),
    message: v.string(),
    profileImageId: v.optional(v.id("_storage")),
    profileImageUrl: v.optional(v.string()),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    profileSlug: v.optional(v.string()),
    linkedinUrl: v.optional(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }),

  timeline: defineTable({
    year: v.string(),
    title: v.string(),
    description: v.string(),
    isActive: v.boolean(),
    order: v.number(),
  }),

  companyValues: defineTable({
    title: v.string(),
    description: v.string(),
    icon: v.string(),
    isActive: v.boolean(),
    order: v.number(),
  }),

  testimonials: defineTable({
    name: v.string(),
    role: v.string(),
    company: v.string(),
    quote: v.string(),
    rating: v.number(),
    serviceId: v.optional(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }),

  clients: defineTable({
    name: v.string(),
    logoUrl: v.optional(v.string()),
    logoImageId: v.optional(v.id("_storage")),
    cloudinaryPublicId: v.optional(v.string()),
    cloudinarySecureUrl: v.optional(v.string()),
    websiteUrl: v.optional(v.string()),
    isActive: v.boolean(),
    order: v.number(),
  }),

  teamPageOrder: defineTable({
    page: v.string(),          // e.g. "about", "web-development", "cybersecurity"
    employeeIds: v.array(v.string()), // employee _id strings in desired display order
  }).index("by_page", ["page"]),

  companyInfo: defineTable({
    name: v.string(),
    email: v.string(),
    phone: v.string(),
    address: v.object({
      street: v.string(),
      landmark: v.string(),
      city: v.string(),
      state: v.string(),
      pincode: v.string(),
      country: v.string(),
    }),
    social: v.object({
      instagram: v.string(),
      linkedin: v.string(),
      youtube: v.string(),
    }),
    stats: v.object({
      projectsCompleted: v.string(),
      clientSatisfaction: v.string(),
      yearsExperience: v.string(),
      teamMembers: v.string(),
      supportAvailability: v.string(),
    }),
  }),

  cloudinaryConfig: defineTable({
    cloudName: v.string(),
    apiKey: v.string(),
    isConfigured: v.boolean(),
  }),
});
